var elementsFromJson=[
    {
        "id":1,
        "letter":"x",
        "rarity":"common",
        "coef":1.3,
        "picture":"xred.png",
        "color":["red"]       
    },
    {
        "id":2,
        "letter":"x",
        "rarity":"common",
        "coef":1.3,
        "picture":"xgreen.png",
        "color":["green"]       
    },
    {
        "id":3,
        "letter":"y",
        "rarity":"common",
        "coef":1.4,
        "picture":"yblue.png",
        "color":["blue"]       
    },
    {
        "id":4,
        "letter":"y",
        "rarity":"common",
        "coef":1.4,
        "picture":"yyellow.png",
        "color":["yellow"]       
    },
    {
        "id":5,
        "letter":"z",
        "rarity":"common",
        "coef":1.5,
        "picture":"zpurple.png",
        "color":["purple"]       
    },
    {
        "id":6,
        "letter":"z",
        "rarity":"common",
        "coef":1.5,
        "picture":"zred.png",
        "color":["red"]       
    },
    {
        "id":7,
        "letter":"u",
        "rarity":"common",
        "coef":1.6,
        "picture":"ugreen.png",
        "color":["green"]       
    },
    {
        "id":8,
        "letter":"u",
        "rarity":"common",
        "coef":1.6,
        "picture":"ublue.png",
        "color":["blue"]       
    },
    {
        "id":9,
        "letter":"i",
        "rarity":"common",
        "coef":1.6,
        "picture":"iyellow.png",
        "color":["yellow"]       
    },
    {
        "id":10,
        "letter":"i",
        "rarity":"common",
        "coef":1.6,
        "picture":"ipurple.png",
        "color":["purple"]       
    },
    {
        "id":11,
        "letter":"m",
        "rarity":"common",
        "coef":1.9,
        "picture":"mred.png",
        "color":["red"]       
    },
    {
        "id":12,
        "letter":"o",
        "rarity":"common",
        "coef":1.9,
        "picture":"oblue.png",
        "color":["blue"]       
    },
    {
        "id":13,
        "letter":"t",
        "rarity":"common",
        "coef":1.9,
        "picture":"tpurple.png",
        "color":["purple"]       
    },
    {
        "id":14,
        "letter":"l",
        "rarity":"legendary",
        "coef":1.2,
        "picture":"legendary.png",
        "color":["yellow","red","purple","blue","green"]       
    }
]